openapi: 3.0.3
info:
  title: coco-backend API
  version: 0.1.0
paths:
  /teams:
    get:
      summary: チーム一覧を取得する
      operationId: getTeams
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
components:
  schemas:
    Team:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
